language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - llvm-7.0
            - clang-7.0
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - sudo apt-get update
    - sudo apt-get install -y
        libboost-test-dev
        libboost-program-options-dev
    - shopt -s expand_aliases
    - alias clang-static-analyzer="scan-build
        --use-cc=`which $CC`
        --use-c++=`which $CXX`
        --force-analyze-debug-code
        -enable-checker core
        -enable-checker cplusplus
        -enable-checker deadcode
        -enable-checker nullability
        -enable-checker security
        -enable-checker unix
        -v -v -v"

script:
    - mkdir build
    - cd build
    - |
      if [[ $CC == clang* ]]
      then
        BUILD_DIR="${TRAVIS_BUILD_DIR}" && \
        clang-static-analyzer cmake \
            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-header-filter=${BUILD_DIR};" \
            -DCMAKE_BUILD_TYPE=Debug \
            .. && \
        clang-static-analyzer cmake --build .
      fi
    - rm -rf *
    - cmake -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Werror" ..
    - cmake --build .
    - ctest
